export type AIProvider = 'openai' | 'anthropic' | 'gemini';

export interface AICompletionOptions {
  apiKey: string;
  provider: AIProvider;
  model?: string;
  prompt: string;
  messages?: Array<{
    role: 'system' | 'user' | 'assistant';
    content: string;
  }>;
}

export interface AIServiceResponse {
  text: string;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

/**
 * Adapter service for Bring Your Own Key (BYOK) AI API interactions.
 * Currently a stub as requested, simulating provider execution.
 */
export const generateAICompletion = async (
  options: AICompletionOptions
): Promise<AIServiceResponse> => {
  const providerName = options.provider.toUpperCase();
  const modelName = options.model || (options.provider === 'openai' ? 'gpt-4' : options.provider === 'anthropic' ? 'claude-3' : 'gemini-1.5-pro');

  console.log(`[AI ADAPTER STUB] Invoking provider [${providerName}] using model [${modelName}]`);
  console.log(`[AI ADAPTER STUB] Prompt Length: ${options.prompt.length} chars. API Key prefix: ${options.apiKey.substring(0, 7)}...`);

  // Simulate networking delay
  await new Promise((resolve) => setTimeout(resolve, 500));

  return {
    text: `This is a mock AI response generated by the BYOK ${providerName} adapter using model ${modelName}. Received prompt: "${options.prompt.substring(0, 60)}..."`,
    usage: {
      promptTokens: Math.ceil(options.prompt.length / 4),
      completionTokens: 40,
      totalTokens: Math.ceil(options.prompt.length / 4) + 40,
    },
  };
};
